[package]
org = "ballerina"
name = "jballerina.java.arrays"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["java", "arrays"]
repository = "https://github.com/ballerina-platform/module-ballerina-jballerina.java.arrays"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0-20250226-081700-17d84e0f"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../test-utils/build/libs/jballerina.java.arrays-test-utils-@project.version@.jar"
version = "@project.version@"
scope = "testOnly"
