[package]
org = "ballerina"
name = "jballerina.java.arrays"
version = "1.5.0"
authors = ["Ballerina"]
keywords = ["java", "arrays"]
repository = "https://github.com/ballerina-platform/module-ballerina-jballerina.java.arrays"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../test-utils/build/libs/jballerina.java.arrays-test-utils-1.5.0.jar"
version = "1.5.0"
scope = "testOnly"
